header:
  version: 14

machine: coral-dev
distro: fslc-xwayland 
target:
  - core-image-base

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    path: sources/bitbake
    layers:
      .: excluded
 
  poky:
    url: "git://git.yoctoproject.org/poky"
    branch: scarthgap
    path: sources/poky
    layers:
      meta:
      meta-poky:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: sources/meta-openembedded
    branch: scarthgap
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-multimedia:
      meta-filesystems:

  meta-freescale:
    url: "https://github.com/Freescale/meta-freescale.git"
    branch: scarthgap
    path: "sources/meta-freescale"
    patches:
      0001_workaround_imx-uboot-compile-issue:
        repo: "meta-coral"
        path: "patches/0001_workaround_imx-uboot-compile-issue.patch"

    
  meta-freescale-3rdparty:
    url: "https://github.com/Freescale/meta-freescale-3rdparty.git"
    branch: scarthgap
    path: "sources/meta-freescale-3rdparty"
 
  meta-freescale-distro:
    url: "https://github.com/Freescale/meta-freescale-distro.git"
    branch: scarthgap
    path: "sources/meta-freescale-distro"
  
  meta-coral:
    url: "https://github.com/public-radiation/meta-coral.git"
    branch: master
    path: "sources/meta-coral"

  meta-clang:
    url: "https://github.com/kraj/meta-clang.git"
    branch: scarthgap
    path: "sources/meta-clang"
    
bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  coral-dev: |
    ACCEPT_FSL_EULA = "1"
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"   
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_ipk"
    INIT_MANAGER = "systemd"
    IMAGE_INSTALL:append = " \
      python3-edgetpu-examples \
    "