header:
  version: 14

machine: coral-dev
distro: fslc-xwayland 
target:
  - core-image-base

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    path: sources/bitbake
    commit: "d251668d9a7a8dd25bd8767efb30d6d9ff8b1ad3"
    layers:
      .: excluded
 
  poky:
    url: "git://git.yoctoproject.org/poky"
    branch: scarthgap
    path: "sources/poky"
    commit: "2034fc38eb4e63984d9bd6b260aa1bf95ce562e4"
    layers:
      meta:
      meta-poky:
    patches:
      0004_apply_poky_fetc_patchset.patch:
        repo: "meta-coral"
        path: "patches/0004_apply_poky_fetc_patchset.patch"

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: "sources/meta-openembedded"
    branch: scarthgap
    commit: "735ae0310870ffce07ce0c55c4f87c20ac161ff9"
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-multimedia:
      meta-filesystems:

  meta-freescale:
    url: "https://github.com/Freescale/meta-freescale.git"
    branch: scarthgap
    commit: "7e2d72128f06568d2359d4fbe8f9c18e1295ea38"
    path: "sources/meta-freescale"
    patches:
      0001_workaround_imx-uboot-compile-issue:
        repo: "meta-coral"
        path: "patches/0001_workaround_imx-uboot-compile-issue.patch"

  meta-freescale-3rdparty:
    url: "https://github.com/Freescale/meta-freescale-3rdparty.git"
    branch: scarthgap
    path: "sources/meta-freescale-3rdparty"
    commit: "6c063450d464eb2f380443c7d9af1b94ce9b9d75"
 
  meta-freescale-distro:
    url: "https://github.com/Freescale/meta-freescale-distro.git"
    branch: scarthgap
    path: "sources/meta-freescale-distro"
    commit: "b9d6a5d9931922558046d230c1f5f4ef6ee72345"
  
  meta-coral:
    url: "https://github.com/public-radiation/meta-coral.git"
    branch: master
    path: "sources/meta-coral"

  meta-clang:
    url: "https://github.com/kraj/meta-clang.git"
    branch: scarthgap
    path: "sources/meta-clang"
    commit: "2b7433611d80f6d0ee1b04156fa91fc73d3c2665"

  meta-swupdate:
    url : "https://github.com/sbabic/meta-swupdate.git"
    refspec : scarthgap
    path: "sources/meta-swupdate"
    commit: "3421a7063a58e4e027130326ab3acccbe3230b30"
    
bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  standard: |
    CONF_VERSION = "2"
  meta-freescale: |
    ACCEPT_FSL_EULA = "1"
  diskmon: |
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
  meta-init-system: |
    PACKAGE_CLASSES = "package_ipk"
    INIT_MANAGER = "systemd"
  meta-coral: |  
    IMAGE_INSTALL:append = " python3-edgetpu-examples "
  penko: |
    IMAGE_INSTALL:append = " omega-portal-server "
    IMAGE_INSTALL:append = " strace openssh"
  oldest_kernel: |
    OLDEST_KERNEL = "5.4"
  root_user: |
    INHERIT += "extrausers"
    EXTRA_USERS_PARAMS = "usermod -p '' root;"
  swupdate: |
    PREFERRED_PROVIDER_u-boot-fw-utils = "libubootenv"
    IMAGE_INSTALL:append = " \
        liberation-fonts \
        libubootenv-bin \
        swupdate \
        swupdate-progress \
        swupdate-tools-ipc \
        swupdate-www \
        kernel-devicetree \
        kernel-image \
        kernel-modules \
    "
    IMAGE_FSTYPES += " ext4.gz wic.gz "
    IMAGE_BOOT_FILES += "flash.bin"
    #IMAGE_FSTYPES_append = " ext4.gz "
    #PREFERRED_VERSION_swupdate = "2020.04+git%"
