header:
  version: 14

machine: coral-dev
distro: fslc-xwayland
target:
  - core-image-base

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: scarthgap
    layers:
      meta:

  meta-freescale:
    url: "https://github.com/Freescale/meta-freescale.git"
    branch: scarthgap
    layers:
      meta-freescale:

  fsl-community-bsp-base: 
    url: "https://github.com/Freescale/fsl-community-bsp-base.git"
    branch: scarthgap
    layers:
      fsl-community-bsp-base:

  meta-freescale-3rdparty:
    url: "https://github.com/Freescale/meta-freescale-3rdparty.git"
    branch: scarthgap
    layers:
      meta-freescale-3rdparty:

  meta-freescale-distro:
    url: "https://github.com/Freescale/meta-freescale-distro.git"
    branch: scarthgap
    layers:
      meta-freescale-distro:

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    branch: scarthgap
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-coral:
    url: "https://github.com/public-radiation/meta-coral.git"
    branch: master
    layers:
      meta-coral:

  meta-clang:
    url: "https://github.com/kraj/meta-clang.git"
    branch: scarthgap
    layers:
      meta-clang:

local_conf_header:
  nxp: |
    ACCEPT_FSL_EULA = "1"

    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    # EXTRA_IMAGE_FEATURES = "debug-tweaks"
